language: dart

dart:
  - 2.10.2
  - dev

dart_task:
  - test:
  - dartanalyzer: --fatal-infos --fatal-warnings .

matrix:
  include:
    # Only validate formatting using the dev release
    - dart: dev
      dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [main]

cache:
 directories:
   - $HOME/.pub-cache
