name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze_strong:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:dev
    steps:
    - uses: actions/checkout@v2
    - run: pub get
    - run: dartanalyzer --fatal-warnings --fatal-infos .

  analyze:
    strategy:
      matrix:
        dart: [latest, beta]
    runs-on: ubuntu-latest
    container:
      image:  google/dart:${{ matrix.dart }}
    steps:
    - uses: actions/checkout@v2
    - run: pub get
    - run: dartanalyzer --fatal-warnings .

  dartfmt:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - run: dartfmt -n .

  test:
    strategy:
      matrix:
        dart: [dev, latest, beta]
    runs-on: ubuntu-latest
    container:
      image:  google/dart:${{ matrix.dart }}
    steps:
    - uses: actions/checkout@v2
    - run: pub get
    - run: pub run test
