name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  runs-on: ubuntu-latest

  container:
    image:  google/dart:latest

jobs:
  setup:

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
  analyze:
    needs: setup
    steps:
    - run: dartanalyzer --fatal-warnings --fatal-infos .
  dartfmt:
    needs: setup
    steps:
    - run: dartfmt -n .
  test:
    needs: setup
    steps:
    - run: pub run test
