name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - run: pub get
    - run: dartanalyzer --fatal-warnings --fatal-infos .
  dartfmt:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - run: dartfmt -n .
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - run: pub get
    - run: pub run test
