name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
  analyze:
    needs: setup
    run: dartanalyzer --fatal-warnings --fatal-infos .
  dartfmt:
    needs: setup
    run: dartfmt -n .
  test:
    needs: setup
    run: pub run test
