name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze_strong:
    runs-on: ubuntu-latest
      runs-on: ubuntu-latest
      steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - run: pub get
      - run: dartanalyzer --fatal-warnings --fatal-infos .

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: cedx/setup-dart@v2
      with:
        release-channel: stable
    - uses: actions/checkout@v2
    - run: pub get
    - run: dartanalyzer --fatal-warnings .

  dartfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: cedx/setup-dart@v2
      with:
        release-channel: dev
    - uses: actions/checkout@v2
    - run: dartfmt -n .

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        dart: [dev, stable, beta]
    runs-on: ${{matrix.os}}
    steps:
    - uses: cedx/setup-dart@v2
        with:
          release-channel: ${{matrix.sdk}}
    - uses: actions/checkout@v2
    - run: pub get
    - run: pub run test
